### ISSUE TITLE
Does not work with Hebrew words

### ISSUE THREAD

**Issue by yonatanlebo** [Bossett/bsky-feeds#72]
Hi, first of all, great job you did!
Is there a possibility that your code could also recognize words in Hebrew?
I tried using the code and it only recognizes words in the English language.

Thanks.

**Comment by Bossett** [comment]
It should recognise any unicode string - how do you have the match set up? (i.e. an emoji isn't 'English')

Note that the app itself will only show you posts that match your language settings - so your users will need Hebrew selected to see those posts at all.

**Comment by yonatanlebo** [comment]
Hi, thanks for the quick reply!

I took one of the original files and changed the words it was looking for to a Hebrew word.
(In this case I took the dads file)
I also did a test of 
public re = /(?=.*\b(father|אבא)\b)/ims
And he only got me what he found from father.

Maybe this is a problem with mongodb?

**Comment by Bossett** [comment]
Ah, no it's a problem with \b - it can have trouble with mixed left-to-right and right-to-left and other unicode. If you remove \b it should match, but it will also match 'grandfather', etc. (which you may want)

**Comment by yonatanlebo** [comment]
Thank you very much!
I will check it in the morning and will update

**Comment by yonatanlebo** [comment]
Looks like it works, thank you!
